#include <iostream>
#include <vector>
#include <algorithm>
#include <string>
#include <queue>
#include <stack>
#include <deque>
#include <set>
#include <map>
#include <unordered_set>
#include <unordered_map>
#include <utility>
#include <tuple>
#include <cmath>
#include <cstring>
#include <cassert>
#include <climits>
#include <cfloat>
#include <iomanip> 
#include <sstream> 
#include <variant>
#include <fstream>
#include <stdexcept>
#include <utility>
#include <filesystem>
#include <type_traits>
#include <type_traits>